---
language: c
dist: xenial
compiler:
  - gcc

before_install:
  - sudo apt-get install -y pamtester tacacs+
  - autoreconf -i

# https://scan.coverity.com/travis_ci
addons:
  apt:
    update: true
  coverity_scan:
    project:
      name: kravietz/pam_tacplus
      version: 1.5.0-pre
      description: Travic-CI scan
    notification_email: pawel.krawczyk@hush.com
    build_command_prepend: ./configure
    build_command: make
    branch_pattern: master

# https://docs.travis-ci.com/user/encryption-keys/
env:
  global:
    secure: ueAz7nQjmf8kNDogfspWYzPwqLakoszpqQBRSj9jxBO6dDFpadfX8Sbsy7F5qpTpu+QrHb1QPybGUSbHS2ris3WyWsLZXGydpc4M5ynggTWVS151IvuT1ASKAMHCRRtN8tBWtjYj1bARnQLhnHA20aWR266b+07e4Sl755qaX4MozP2k+tqbaUYSIVqXDJIXPwEIHMIPIrsmsOtOuwktUX3zvjE145eCpGjzLIDCoay18W+wtO6KQ44to3sDIihA8i44eo2a87z1aPuvv5WAUKP/is0c270okuwiNr0KHI5g6ke1/fYphLKFioA1AbLidOmvoxIIpvkSHMyr0hYiSJIjgIvr6xKhU1XuF6Ohvn5PqsKORXJa67rtDIDZSlQZkvojAFx6yQ8F2BXjQECzbWBNeJ7JRpinKBep6qSn5qz96eufQQrn/85zwYPSXfyh5GJ8AMKDI2Tx4XBk5u5sV7fTryITwQO4FdGPQsJlKgFa1568sQC2UDNiL+yUOA/4FEOrbjXhzBwjukyMR9wtLCqGVHrU/93Ub7PbJLbaJxhldm+o/TY/xUBzSP/BWRgNPoKBteAK4N2JhYyzDvEflEA5SfgGgjhlf4Z8FhaPw/rk13aqq02mKALe8z3fK6WUlT1eqhlNjZ5AGqudy2qL2hbgsMAEIaflQcabUv7BRGw=
